[preload  storage="./data/bgimage/[0-0].png"  ]
[preload  storage="./data/bgimage/[7-1].jpg"  ]
[preload  storage="./data/bgimage/[0-41].jpg"  ]
[preload  storage="./data/bgimage/[1-1].jpg"  ]
[return]